import SectionLabel from '../components/SectionLabel'

const labs = [
  { title: 'Kubernetes', text: 'K3s, namespaces, services, ingress, Helm et déploiements cloud-native.', detail: 'Construire un cluster assez petit pour être compris, mais assez réaliste pour apprendre les vrais chemins d’un workload.', note: 'Je veux savoir ce qui se passe entre un manifeste appliqué et une URL réellement disponible.', image: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=900&q=82' },
  { title: 'Networking', text: 'DNS, reverse proxy, TLS, VLAN, services internes et exposition contrôlée.', detail: 'Cartographier les flux avant de les exposer : chaque port ouvert doit avoir une raison, une limite et un signal.', note: 'Le réseau est souvent invisible quand tout va bien ; le lab sert à le rendre lisible avant la panne.', image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=82' },
  { title: 'Observability', text: 'Prometheus, Grafana et Loki pour métriques, dashboards et logs.', detail: 'Relier métriques, logs et événements pour passer de “ça ne marche plus” à une hypothèse vérifiable.', note: 'Un bon dashboard ne décore pas le lab : il aide à décider quoi faire ensuite.', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=82' },
  { title: 'Virtualization', text: 'Proxmox et machines de lab pour construire des environnements reproductibles.', detail: 'Isoler les expérimentations, créer des snapshots et recommencer sans transformer chaque erreur en catastrophe.', note: 'La possibilité de revenir en arrière rend les idées plus audacieuses et les apprentissages plus rapides.', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=82' },
  { title: 'Containers', text: 'Docker, images, réseaux, volumes et bonnes pratiques de runtime.', detail: 'Comprendre ce qui entre dans une image, ce qui persiste dans un volume et ce qui doit rester éphémère.', note: 'Un conteneur propre est un contrat clair entre le code, l’environnement et la plateforme.', image: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&w=900&q=82' },
  { title: 'Automation', text: 'GitHub Actions, CI/CD, Ansible et Terraform au fil de la progression.', detail: 'Transformer les commandes répétées en étapes versionnées, rejouables et compréhensibles par quelqu’un d’autre.', note: 'L’automatisation commence quand la mémoire ne suffit plus ; la documentation lui donne une direction.', image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=82' },
]

export default function Labs() {
  return <section className="page section">
    <SectionLabel>LABS / 02</SectionLabel>
    <div className="page-header page-header-split"><div><p className="kicker">TECHNICAL LAB</p><h1>Build it.<br/><span>Break it.</span></h1><p>Un environnement d'expérimentation où chaque service devient une occasion d'apprendre l'architecture, l'exploitation, la sécurité et l'automatisation.</p></div><div className="editorial-visual lab-visual"><img src="https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=85" alt="Racks de serveurs dans un datacenter" loading="lazy"/><div className="visual-scan"/><div className="visual-caption"><span>LAB / 002</span><strong>OBSERVE EVERYTHING</strong></div><div className="telemetry"><i/><span>NODE_03</span><b>ONLINE</b></div></div></div>
    <div className="lab-grid">{labs.map(({ title, text, detail, note, image }, i) => <article className="detail-card visual-card lab-card" key={title}><div className="card-visual"><img src={image} alt={`${title} technical lab`} loading="lazy"/><span>LAB / 0{i + 1}</span></div><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p><p className="lab-detail">{detail}</p><blockquote className="lab-note">“{note}”</blockquote></article>)}</div>
  </section>
}
